import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from "next/head";
import Box from "@mui/material/Box";
import Sidebar from '@/components/Sidebar';
import { io } from "socket.io-client";
const socket = io("http://localhost:8000/");
var Id = "";
socket.on("connect", () => {
  Id = `${socket.id}`;
  console.log(`you connected with id=${socket.id}`);
});
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Chat App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Sidebar userId={Id} />
      </div>
    </>
  );
}
